services:
  app:
    build: .
    environment:
      PG_DB: pollit
      PG_HOST: postgres
      PG_USER: postgres
      PG_PASSWORD: mypassword
    ports:
      - '3000:3000'
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_DB: pollit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - '5432:5432'
    volumes:
      - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
