services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_DB: pollit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - '5432:5432'
    # volumes:
    #   - ./psql-cities-data/world.sql:/docker-entrypoint-initdb.d/world.sql
